; Steam Auto-Updater client configuration
[AutoUpdater]
server_url=http://127.0.0.1:8000
api_key=zOTHOQY4gcdx6xSg5RzT-G-u9xJJABivqXjrgz_IlLA
steamcmd_path=d:\Ayder_dontdelete\steamcmd\steamcmd.exe
pc_id=PC-01
